id: P000516
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-16 15:44:04.177054
source_metadata:
  id: bdr:W8LS19963
  title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
  author: ''
  volumes:
    ce08532d1fc643f68a0b391b8ea39f25:
      image_group_id: I1PD36387
      title: Volume 1 of bstan rtsis re'u mig
      volume_number: 1
      total_pages: 360
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
