id: opecha:P000516
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19963
  title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
  volume:
    ce08532d1fc643f68a0b391b8ea39f25:
      image_group_id: I1PD36387
      title: Volume 1 of bstan rtsis re'u mig
      volume_number: 1
      total_pages: 360
  author: ''
ebook_metadata:
  title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
  author: ''
  sku: P000516
  cover: cover.jpg
  layers:
  - pagination
